packages:
  - "."

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': false
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - prisma
  - sharp
  - unrs-resolver
